name: simulate
description: A collection of simulations and visualizations

version: 1.0.0+1

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.4
    url_launcher: ^6.0.18
    provider: ^6.0.2
    shared_preferences: ^2.0.12
    flutter_screenutil: ^5.1.0
    flutter_svg: ^1.0.3
    math_expressions: any
    equatable: ^1.1.1
    uuid: ^2.0.4
    line_awesome_icons: ^1.0.4+2
    flutter_colorpicker: ^0.3.4
    rflutter_alert: ^2.0.4
    sweetalert: any
    sweetalertv2: any
    youtube_player_flutter: any
    get: ^4.3.8
    http: ^0.13.4
    universal_html: any
    webview_flutter_web: ^0.1.0+1
    easy_web_view: 

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true


    assets:
        - assets/images/
        - assets/simulations/
        - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
        - assets/5.jpg
        - assets/6.jpg
        - assets/7.jpg
        - assets/8.jpg
        - assets/9.jpg

    fonts:
        - family: Ubuntu
          fonts:
              - asset: fonts/Ubuntu-Regular.ttf
